#include <cmath>
#pragma once

// PRED (Predator) Constants
#define MAX_POP_PRED 3
#define MAX_POP_PRED_PERCENT 1.0
#define PRED_GAIN_ENERGY_EATING 92
#define PRED_LOST_ENERGY_FIGHT_BY_PREY 1600
#define PRED_PASSIVE_ENERGY_LOSS 1
#define PRED_N_MIN_CHILDREN 1
#define PRED_N_MAX_CHILDREN 1
#define PRED_LOST_ENERGY_FIGHT 0
#define PRED_MAX_VELOCITY 10
#define PRED_MAX_RAY_ANGLE M_PI_2
#define PRED_START MAX_POP_PRED * MAX_POP_PRED_PERCENT

// PREY (Prey) Constants
#define MAX_POP_PREY 2
#define MAX_POP_PREY_PERCENT 1.0
#define PREY_LOST_ENERGY_FIGHT_BY_PRED 733
#define PREY_PASSIVE_ENERGY_LOSS 0
#define PREY_N_MIN_CHILDREN 1
#define PREY_N_MAX_CHILDREN 1
#define PREY_MAX_VELOCITY 7
#define PREY_MAX_RAY_ANGLE M_PI_2
#define PREY_START MAX_POP_PREY * MAX_POP_PREY_PERCENT

// TREE Constants
#define TIME_TREE_GROWTH 300
#define TREE_START 3
#define FRUIT_ENERGY 98
#define MAX_TREES_RADIUS 10
#define MIN_TREES_RADIUS 10
#define PROB_TREE_RANDOM_SPAWN 0
#define TREE_RADIUS_BEFORE_REPRODUCTION_PERCENT 0.8

// SYSTEM Constants
#define MAX_ENERGY 2568
#define ROT_TIME 381
#define REPRODUCTION_TIMEOUT 102
#define MAX_HEALTH 1500
#define WINDOW_HEIGHT 200
#define WINDOW_WIDTH 200
#define ANIMALS_RADIUS 9
#define INITIAL_ENERGY MAX_ENERGY * 0.8
#define NB_RAY 8
#define RAY_LENGTH 70
#define LOST_ENERGY_REPRODUCTION 10
#define INVISIBILITY_TIME 1000
#define MUTATION_RATE 0.75
#define PROB_ADD_CONNECTION 0.15
#define PROB_ADD_NEURON 0.15
#define RADIUS_PERCENT_ROTTING 0.8
#define ROTTING_PER_FRAME 1