#include <cmath>
#pragma once

#define MAX_POP_PRED 200
#define MAX_POP_PREY 230
#define TREE_START 390
#define FRUIT_ENERGY 160
#define TIME_TREE_GROWTH 347.6952124249924
#define MAX_ENERGY 3150
#define ROT_TIME 450
#define LOST_ENERGY_REPRODUCTION 30
#define REPRODUCTION_TIMEOUT 190
#define PRED_GAIN_ENERGY_EATING 140
#define PRED_LOST_ENERGY_FIGHT_BY_PREY 200
#define PRED_PASSIVE_ENERGY_LOSS 6
#define PRED_N_MIN_CHILDREN 1
#define PRED_N_MAX_CHILDREN 4
#define INVISIBILITY_TIME 2700
#define PREY_LOST_ENERGY_FIGHT_BY_PRED 2000
#define PREY_PASSIVE_ENERGY_LOSS 2
#define PREY_N_MIN_CHILDREN 2
#define PREY_N_MAX_CHILDREN 4
#define WINDOW_HEIGHT 800
#define WINDOW_WIDTH 800
#define PRED_START MAX_POP_PRED / 2
#define PREY_START MAX_POP_PREY / 2
#define MAX_TREES_RADIUS 12
#define MIN_TREES_RADIUS 2
#define PROB_TREE_RANDOM_SPAWN 0.2
#define ANIMALS_RADIUS 9
#define INITIAL_ENERGY MAX_ENERGY * 0.8
#define MAX_HEALTH MAX_ENERGY
#define MUTATION_RATE 0.8
#define PROB_ADD_CONNECTION 0.25
#define PROB_ADD_NEURON 0.08
#define NB_RAY 8
#define RAY_LENGTH 101
#define PRED_LOST_ENERGY_FIGHT 0
#define PRED_MAX_VELOCITY 7
#define PRED_MAX_RAY_ANGLE M_PI_2
#define PREY_MAX_VELOCITY 5
#define PREY_MAX_RAY_ANGLE M_PI_2
