#pragma once
#include <cmath>

// simulation
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 800
#define MAX_POP_PRED 180000
#define MAX_POP_PREY 180000
#define PRED_START 80//MAX_POP_PRED * .5f
#define PREY_START 400//MAX_POP_PREY * .7f
#define TREE_START 1000

// trees
#define TREES_RADIUS 12
#define FRUIT_ENERGY 60
#define TIME_TREE_GROWTH 400.

// animals
#define ANIMALS_RADIUS 8
#define INITIAL_ENERGY 400
#define MAX_ENERGY 800
#define MUTATION_RATE .08
#define NB_RAY 8
#define RAY_LENGTH 101
#define ROT_TIME 200
#define LOST_ENERGY_REPRODUCTION 0
#define REPRODUCTION_TIMEOUT 80

// predators
#define PRED_GAIN_ENERGY_EATING 140
#define PRED_LOST_ENERGY_FIGHT 0
#define PRED_LOST_ENERGY_FIGHT_BY_PREY MAX_ENERGY/6
#define PRED_MAX_VELOCITY 8
#define PRED_MAX_RAY_ANGLE M_PI_2
#define PRED_N_MIN_CHILDREN 2
#define PRED_N_MAX_CHILDREN 4

// preys
#define INVISIBILITY_TIME 1000
#define PREY_LOST_ENERGY_FIGHT MAX_ENERGY/2
#define PREY_MAX_VELOCITY 5
#define PREY_MAX_RAY_ANGLE M_PI*2*.7
#define PREY_N_MIN_CHILDREN 2
#define PREY_N_MAX_CHILDREN 5
